chinchang/web-maker

- src/index.html
- src/lib/codemirror/mode/jsx/jsx.js
- src/manifest.json
- src/script.js
- src/style.css
- autocompletion! #43 
- sass support #45 
- fullscreen preview #24 
- faster css update #22 
- bugfix: indentation #46
- bugfix: chrome canary csp fix #39
> Release 2.2

- src/script.js
- src/style.css
> Release 2.2.2

- src/index.html
- src/script.js
- bugfix for main split size saving
- use title for file name when saving as html
> Release 2.3.1

- .eslintrc.json
- src/dropdown.js
- src/index.html
- src/lib/atomizer.browser.js
- src/script.js
- src/style.css
- src/utils.js
- Atomic CSS Support! (without configuration for now) #100 
- Configurable auto preview #60 
- Configurable refresh on resize #97 
- Search (by title) in saved creations #26 
- Fix indentation bug #104
> Release 2.5

- src/library-list.js
> newer versions

- src/index.html
- src/script.js
Ability to configure whether to preserve console logs on preview refresh or not.
> New setting for preserving console logs.

- src/index.html
- src/script.js
- src/style.css
On some machines that blur overlay just kills the performance.
Would be nice to have the option to disable it.
> Add option to toggle faster/lighter version of extension

- src/changelog.html
- src/detached-window.js
- src/index.html
- src/lib/screenlog.js
- src/library-list.js
- src/manifest.json
- src/preview.html
- src/script.js
- src/style.css
- Detached preview #92 
- Find/replace in code #20 
- Atomizer configurations #109 
- **New Settings** - Light/fast mode for low-end devices #172 
- **New Setting** - Preserve logs across preview refreshes #181 
- **New Settings**: Word wrapping #186 
- Add semantic UI to popular libraries #189 
- Update popular libraries to latest version. You heard Bootstrap 4 is in Beta now? #192 
- Add help tooltips to all settings #165 
- Upapted settings UI
- **Bugfix** - Anytime trigger preview refresh with Ctr/Cmd + Shift + 5
> Release 2.9

- src/manifest.json
> Corrected a typo in Readme File

- .gitignore
- src/script.js
As mentioned in Issue #209 
**Demo**
> Retina screenshot Fix

- src/style.css
> Fixed z-index

- src/library-list.js
For now Web Maker does not support import/require statements
So CommonJs libs are useless. Use UMD.
> Use UMD React and ReactDOM

- .prettierignore
- .prettierrc
- git-hooks/pre-commit
- src/index.html
- src/lib/codemirror/lib/codemirror.js
- src/script.js
- src/service-worker-registration.js
- src/style.css
> Mobile support

- src/components/Footer.jsx
- src/components/MainHeader.jsx
- src/components/Modal.jsx
- src/components/Notifications.jsx
- src/components/common.jsx
- src/style.css
closes #276
I decided to keep the custom 'buttons' for tracking.
Let me know what you think.
> fix(anchors): move anchors to buttons when more appropriate

- src/components/Console.jsx
- src/components/ContentWrap.jsx
- src/components/app.jsx
- src/style.css
Remove the dirty approach of shifting console DOM here and there in detached mode. Now just CSS works!
> Fix 319 console detached

- package.json
- src/components/ContentWrapFiles.jsx
- src/components/FileIcon.jsx
- src/components/app.jsx
- src/fileUtils.js
- src/tests/fileUtils.test.js
- src/utils.js
> add prettier support for formatting files

- src/assets/vue-logo.svg
- src/templateList.js
- src/templates/template-vue.json
Meant to address #334 - just a simple Vue template.
> Add Vue Template

- src/assets/vue-logo.svg
- src/libraryList.js
- src/templateList.js
- src/templates/template-vue.json
> Release 3.5

- .babelrc
- src/components/Console.jsx
- src/components/ContentWrap.jsx
- src/components/ContentWrapFiles.jsx
- src/components/SplitPane.jsx
- src/components/UserCodeMirror.jsx
- src/components/app.jsx
- src/style.css
> Preview dimension 317

- src/components/Settings.jsx
- src/components/Switch.jsx
- src/components/Tabs.jsx
- src/components/app.jsx
- src/components/common.jsx
- src/style.css
> Settings ui refactor

- src/itemService.js
add missing import statement to fix the error when delete a document.
> fix-379-add-missing-import-statement-to-fix-the-error-when-delete-a-document.

- src/libraryList.js
According to the creator of Lodash, Lodash has better performance, more features and optimisation for larger arrays and object iterations.
> Added Lodash to JS libraries

- src/components/AddLibrary.jsx
- src/manifest.json
> Add tailwind CDN to CSP and bump minor version

- package.json
- src/components/Notifications.jsx
- src/components/app.jsx
- src/manifest.json
> Release v4.2.0

- gulpfile.js
- package.json
- there is no vendor.js file hence removed the minifyJs call on that
- added callback function parameter to the anonymous function of release
and devRelease
> Fixes in the gulpfile

- src/components/Dropdown.jsx
- src/components/Footer.jsx
- src/components/app.jsx
- src/style.css
- src/utils.js
- Adds support for inline assets in HTML
- Supports images, audio and video
partially fixes #560
> Html inlining
